java_test(
    name = "SolutionTest",
    size = "small",
    srcs = ["SolutionTest.java"],
    deps = [
        "//demo_bazel/src/main/java/com/dynamo/demobazel/leetcodes/Q802:LeetcodesQ802"
    ],
)