java_library(
    name = "Sorts",
    srcs = glob(["*.java"]),
    visibility = [
        "//demo_bazel/src/test/java/com/dynamo/demobazel/algo/sorts:__pkg__",
    ],
    deps = [
        "//demo_bazel/src/main/java/com/dynamo/demobazel/algo/utils:SortUtils",
    ],
)
