java_library(
    name = "Sorts",
    srcs = glob(["*.java"]),
    visibility = [
        "//demo_bazel/src/test/java/com/dynamo/demobazel/algo:__pkg__",
    ],
    deps = [
        # "//plugins:autovalue",
    ],
)
