java_library(
    name = "AdapterPatterns",
    srcs = glob([
        "*.java",
    ]),
    visibility = [
    ],
)

java_binary(
    name = "AdapterPatternsApp",
    main_class = "com.dynamo.demobazel.algo.patterns.adapter.App",
    runtime_deps = [":AdapterPatterns"],
)
